### ISSUE TITLE
Actuate doesn't work in FF and IE11

### ISSUE THREAD

**Issue by SteFlemmer** [lukejacksonn/Actuate#3]
The Check to select the needed Eventname fails in Firefox and IE11. This causes Actuate to never get the "animationend" Event, because it was not set correctly. Also in IE11 classList.add or .remove can't be used with multiple values.

**Comment by SteFlemmer** [comment]
I tested it in my Project with Chrome, FF, IE11, Edge, Safari.  Animationend is supported by all major browsers now, so the additional check is not needed. See https://caniuse.com/#search=animationend

**Comment by lukejacksonn** [comment]
Hey 👋🏼 thanks for reporting and triaging this! I am currently on holiday but will try look at the PR asap. Please nudge me again if I forget.

**Comment by lukejacksonn** [comment]
There is now a new version published on npm here: https://unpkg.com/actuatejs 🎉
